export const languages = [
  { id: "en", label: "English", flag: "🇺🇸", locale: "en-US" },
  { id: "es", label: "Español", flag: "🇪🇸", locale: "es-ES" },
  { id: "fr", label: "Français", flag: "🇫🇷", locale: "fr-FR" },
  { id: "de", label: "Deutsch", flag: "🇩🇪", locale: "de-DE" },
  { id: "pt", label: "Português", flag: "🇧🇷", locale: "pt-BR" },
  { id: "it", label: "Italiano", flag: "🇮🇹", locale: "it-IT" },
  { id: "nl", label: "Nederlands", flag: "🇳🇱", locale: "nl-NL" },
  { id: "ar", label: "العربية", flag: "🇸🇦", locale: "ar-SA" },
  { id: "hi", label: "हिन्दी", flag: "🇮🇳", locale: "hi-IN" },
  { id: "zh", label: "中文", flag: "🇨🇳", locale: "zh-CN" },
  { id: "ja", label: "日本語", flag: "🇯🇵", locale: "ja-JP" },
  { id: "ko", label: "한국어", flag: "🇰🇷", locale: "ko-KR" },
  { id: "id", label: "Bahasa Indonesia", flag: "🇮🇩", locale: "id-ID" },
  { id: "tr", label: "Türkçe", flag: "🇹🇷", locale: "tr-TR" },
  { id: "ru", label: "Русский", flag: "🇷🇺", locale: "ru-RU" },
] as const;

export type Language = (typeof languages)[number]["id"];
export const LANGUAGE_KEY = "glint.language.v1";

type Copy = Record<string, string>;
const en: Copy = {
  welcomeTitle: "Fuel like a champ.", welcomeSub: "Snap, track, and eat smarter with Glint.", signup: "Sign up with email", login: "Log in", create: "Create account", email: "Email", password: "Password", confirm: "Confirm password", letsGo: "Let's go", back: "Back", privacy: "By continuing, you agree to our Terms. We don't sell your data — promise.",
  assessmentTitle: "Build your game plan", assessmentSub: "Five quick picks. Then Glint personalizes your daily dashboard.", step: "Step", of: "of", nameQ: "What should your coach call you?", nameP: "Your first name", goalQ: "What are you training for?", activityQ: "How active are your days?", dietQ: "What food style fits you?", focusQ: "What matters most right now?", continue: "Continue", finish: "Start my plan", balanced: "Balanced", muscle: "Build muscle", fatLoss: "Lose fat", energy: "More energy", sedentary: "Mostly seated", light: "Lightly active", moderate: "Moderately active", very: "Very active", athlete: "Athlete", everything: "Everything", vegetarian: "Vegetarian", vegan: "Vegan", pescatarian: "Pescatarian", highProtein: "High protein", consistency: "Consistency", portions: "Portion control", macros: "Hit my macros", betterChoices: "Better food choices",
  greeting: "Ready to fuel up", dailyFuel: "Daily fuel", remaining: "kcal remaining", over: "kcal over goal", carbs: "Carbs", protein: "Protein", fat: "Fat", bodyScan: "Body Scan", bodyScanNew: "Get your physique estimate and a personalized 7-day plan.", rescan: "Tap to view or rescan", mealsToday: "Today's meals", logged: "logged", noMeals: "Your plate is waiting", noMealsSub: "Snap a meal and watch Glint turn it into useful fuel data.", addMeal: "Add meal", editPlan: "Edit plan", goal: "Goal", language: "Language", signOut: "Sign out", logMeal: "Log a meal", pickMethod: "How are we tracking this one?", takePhoto: "Take photo", takePhotoSub: "Use your camera", uploadPhoto: "Upload photo", uploadPhotoSub: "Choose from your gallery", describe: "Describe it", describeSub: "Type what you ate", describeMeal: "Describe your meal", analyze: "Analyze meal", discard: "Discard", analyzing: "Analyzing your meal…", logIt: "Log meal", today: "Today", kcal: "kcal",
};

const local: Record<Language, Copy> = {
  en,
  es: { welcomeTitle:"Come como un campeón.",welcomeSub:"Fotografía, registra y come mejor con Glint.",signup:"Regístrate con email",login:"Iniciar sesión",create:"Crear cuenta",assessmentTitle:"Crea tu plan",assessmentSub:"Cinco respuestas rápidas para personalizar Glint.",nameQ:"¿Cómo debe llamarte tu coach?",goalQ:"¿Cuál es tu objetivo?",activityQ:"¿Qué tan activo eres?",dietQ:"¿Qué estilo de comida prefieres?",focusQ:"¿Qué importa más ahora?",continue:"Continuar",finish:"Empezar mi plan",balanced:"Equilibrio",muscle:"Ganar músculo",fatLoss:"Perder grasa",energy:"Más energía",greeting:"Listo para alimentarte",dailyFuel:"Energía diaria",remaining:"kcal restantes",over:"kcal sobre la meta",bodyScan:"Escaneo corporal",mealsToday:"Comidas de hoy",noMeals:"Tu plato te espera",addMeal:"Añadir comida",editPlan:"Editar plan",language:"Idioma",signOut:"Cerrar sesión",analyze:"Analizar comida" },
  fr: { welcomeTitle:"Mange comme un champion.",welcomeSub:"Photographie, suis et mange mieux avec Glint.",signup:"S'inscrire par e-mail",login:"Connexion",create:"Créer un compte",assessmentTitle:"Crée ton plan",assessmentSub:"Cinq choix rapides pour personnaliser Glint.",nameQ:"Comment ton coach doit-il t'appeler ?",goalQ:"Quel est ton objectif ?",activityQ:"Quel est ton niveau d'activité ?",dietQ:"Quel style alimentaire te convient ?",focusQ:"Quelle est ta priorité ?",continue:"Continuer",finish:"Lancer mon plan",balanced:"Équilibre",muscle:"Prendre du muscle",fatLoss:"Perdre du gras",energy:"Plus d'énergie",greeting:"Prêt à faire le plein",dailyFuel:"Énergie du jour",remaining:"kcal restantes",bodyScan:"Scan corporel",mealsToday:"Repas du jour",noMeals:"Ton assiette t'attend",addMeal:"Ajouter un repas",editPlan:"Modifier le plan",language:"Langue",signOut:"Déconnexion" },
  de: { welcomeTitle:"Iss wie ein Champion.",welcomeSub:"Fotografieren, tracken und smarter essen.",signup:"Mit E-Mail registrieren",login:"Anmelden",create:"Konto erstellen",assessmentTitle:"Erstelle deinen Plan",assessmentSub:"Fünf schnelle Antworten personalisieren Glint.",nameQ:"Wie soll dein Coach dich nennen?",goalQ:"Was ist dein Ziel?",activityQ:"Wie aktiv bist du?",dietQ:"Welcher Ernährungsstil passt?",focusQ:"Was zählt gerade am meisten?",continue:"Weiter",finish:"Plan starten",balanced:"Ausgeglichen",muscle:"Muskelaufbau",fatLoss:"Fett verlieren",energy:"Mehr Energie",greeting:"Bereit zum Auftanken",dailyFuel:"Tagesenergie",remaining:"kcal übrig",bodyScan:"Körperscan",mealsToday:"Heutige Mahlzeiten",noMeals:"Dein Teller wartet",addMeal:"Mahlzeit hinzufügen",editPlan:"Plan bearbeiten",language:"Sprache",signOut:"Abmelden" },
  pt: { welcomeTitle:"Coma como um campeão.",welcomeSub:"Fotografe, acompanhe e coma melhor com Glint.",signup:"Cadastrar com e-mail",login:"Entrar",create:"Criar conta",assessmentTitle:"Monte seu plano",assessmentSub:"Cinco escolhas rápidas para personalizar o Glint.",nameQ:"Como seu coach deve chamar você?",goalQ:"Qual é seu objetivo?",activityQ:"Quão ativo você é?",dietQ:"Qual estilo alimentar combina com você?",focusQ:"O que mais importa agora?",continue:"Continuar",finish:"Começar meu plano",balanced:"Equilíbrio",muscle:"Ganhar músculo",fatLoss:"Perder gordura",energy:"Mais energia",greeting:"Pronto para se abastecer",dailyFuel:"Energia diária",remaining:"kcal restantes",bodyScan:"Escaneamento corporal",mealsToday:"Refeições de hoje",noMeals:"Seu prato está esperando",addMeal:"Adicionar refeição",editPlan:"Editar plano",language:"Idioma",signOut:"Sair" },
  it: { welcomeTitle:"Mangia da campione.",welcomeSub:"Scatta, registra e mangia meglio con Glint.",signup:"Registrati con email",login:"Accedi",create:"Crea account",assessmentTitle:"Crea il tuo piano",assessmentSub:"Cinque scelte rapide per personalizzare Glint.",nameQ:"Come deve chiamarti il coach?",goalQ:"Qual è il tuo obiettivo?",activityQ:"Quanto sei attivo?",dietQ:"Quale stile alimentare preferisci?",focusQ:"Cosa conta di più adesso?",continue:"Continua",finish:"Inizia il piano",balanced:"Equilibrio",muscle:"Aumenta muscoli",fatLoss:"Perdi grasso",energy:"Più energia",greeting:"Pronto a fare il pieno",dailyFuel:"Energia giornaliera",remaining:"kcal rimanenti",bodyScan:"Scansione corpo",mealsToday:"Pasti di oggi",noMeals:"Il tuo piatto ti aspetta",addMeal:"Aggiungi pasto",editPlan:"Modifica piano",language:"Lingua",signOut:"Esci" },
  nl: { welcomeTitle:"Eet als een kampioen.",welcomeSub:"Foto, volg en eet slimmer met Glint.",signup:"Aanmelden met e-mail",login:"Inloggen",create:"Account maken",assessmentTitle:"Maak je plan",assessmentSub:"Vijf snelle keuzes maken Glint persoonlijk.",nameQ:"Hoe mag je coach je noemen?",goalQ:"Waar train je voor?",activityQ:"Hoe actief ben je?",dietQ:"Welke eetstijl past bij je?",focusQ:"Wat telt nu het meest?",continue:"Verder",finish:"Start mijn plan",balanced:"Gebalanceerd",muscle:"Spieren opbouwen",fatLoss:"Vet verliezen",energy:"Meer energie",greeting:"Klaar om bij te tanken",dailyFuel:"Dagelijkse brandstof",remaining:"kcal over",bodyScan:"Lichaamsscan",mealsToday:"Maaltijden vandaag",noMeals:"Je bord wacht",addMeal:"Maaltijd toevoegen",editPlan:"Plan wijzigen",language:"Taal",signOut:"Uitloggen" },
  ar: { welcomeTitle:"تغذَّ كالأبطال.",welcomeSub:"صوّر وتتبع وتناول طعامًا أذكى مع Glint.",signup:"التسجيل بالبريد",login:"تسجيل الدخول",create:"إنشاء حساب",assessmentTitle:"ابنِ خطتك",assessmentSub:"خمسة اختيارات سريعة لتخصيص Glint.",nameQ:"ماذا يناديك مدربك؟",goalQ:"ما هدفك؟",activityQ:"ما مستوى نشاطك؟",dietQ:"ما نمطك الغذائي؟",focusQ:"ما الأهم الآن؟",continue:"متابعة",finish:"ابدأ خطتي",balanced:"متوازن",muscle:"بناء العضلات",fatLoss:"خسارة الدهون",energy:"طاقة أكثر",greeting:"جاهز للتزود بالطاقة",dailyFuel:"طاقة اليوم",remaining:"سعرة متبقية",bodyScan:"فحص الجسم",mealsToday:"وجبات اليوم",noMeals:"طبقك ينتظر",addMeal:"أضف وجبة",editPlan:"عدّل الخطة",language:"اللغة",signOut:"تسجيل الخروج" },
  hi: { welcomeTitle:"चैंपियन की तरह खाएँ।",welcomeSub:"फोटो लें, ट्रैक करें और Glint के साथ बेहतर खाएँ।",signup:"ईमेल से साइन अप",login:"लॉग इन",create:"खाता बनाएँ",assessmentTitle:"अपना प्लान बनाएँ",assessmentSub:"पाँच छोटे जवाब Glint को आपके लिए तैयार करेंगे।",nameQ:"कोच आपको क्या बुलाए?",goalQ:"आपका लक्ष्य क्या है?",activityQ:"आप कितने सक्रिय हैं?",dietQ:"आपकी भोजन शैली क्या है?",focusQ:"अभी सबसे ज़रूरी क्या है?",continue:"आगे",finish:"मेरा प्लान शुरू करें",balanced:"संतुलित",muscle:"मांसपेशियाँ बढ़ाएँ",fatLoss:"वसा घटाएँ",energy:"अधिक ऊर्जा",greeting:"ईंधन भरने को तैयार",dailyFuel:"आज का ईंधन",remaining:"कैलोरी बाकी",bodyScan:"बॉडी स्कैन",mealsToday:"आज का भोजन",noMeals:"आपकी प्लेट इंतज़ार कर रही है",addMeal:"भोजन जोड़ें",editPlan:"प्लान बदलें",language:"भाषा",signOut:"साइन आउट" },
  zh: { welcomeTitle:"像冠军一样吃。",welcomeSub:"拍照、记录，用 Glint 吃得更聪明。",signup:"用邮箱注册",login:"登录",create:"创建账户",assessmentTitle:"制定你的计划",assessmentSub:"五个快速选择，让 Glint 更懂你。",nameQ:"教练该怎么称呼你？",goalQ:"你的训练目标是什么？",activityQ:"你每天有多活跃？",dietQ:"哪种饮食适合你？",focusQ:"现在最重要的是什么？",continue:"继续",finish:"开始我的计划",balanced:"均衡",muscle:"增肌",fatLoss:"减脂",energy:"提升精力",greeting:"准备好补充能量",dailyFuel:"今日能量",remaining:"千卡剩余",bodyScan:"身体扫描",mealsToday:"今日饮食",noMeals:"你的餐盘在等你",addMeal:"添加餐食",editPlan:"编辑计划",language:"语言",signOut:"退出" },
  ja: { welcomeTitle:"チャンピオンのように食べよう。",welcomeSub:"撮って、記録して、Glintでもっと賢く食べよう。",signup:"メールで登録",login:"ログイン",create:"アカウント作成",assessmentTitle:"プランを作ろう",assessmentSub:"5つの簡単な質問でGlintをあなた仕様に。",nameQ:"コーチから何と呼ばれたい？",goalQ:"目標は何ですか？",activityQ:"普段の活動量は？",dietQ:"合う食事スタイルは？",focusQ:"今いちばん大切なことは？",continue:"次へ",finish:"プランを開始",balanced:"バランス",muscle:"筋肉を増やす",fatLoss:"脂肪を減らす",energy:"もっと元気に",greeting:"エネルギー補給の準備OK",dailyFuel:"今日のエネルギー",remaining:"kcal 残り",bodyScan:"ボディスキャン",mealsToday:"今日の食事",noMeals:"お皿が待っています",addMeal:"食事を追加",editPlan:"プラン編集",language:"言語",signOut:"ログアウト" },
  ko: { welcomeTitle:"챔피언처럼 먹어요.",welcomeSub:"찍고, 기록하고, Glint로 더 똑똑하게 먹어요.",signup:"이메일로 가입",login:"로그인",create:"계정 만들기",assessmentTitle:"나만의 계획 만들기",assessmentSub:"다섯 가지 선택으로 Glint를 맞춤 설정해요.",nameQ:"코치가 뭐라고 부를까요?",goalQ:"목표가 무엇인가요?",activityQ:"평소 활동량은?",dietQ:"어떤 식단이 맞나요?",focusQ:"지금 가장 중요한 것은?",continue:"계속",finish:"계획 시작",balanced:"균형",muscle:"근육 증가",fatLoss:"체지방 감량",energy:"에너지 향상",greeting:"에너지 충전 준비 완료",dailyFuel:"오늘의 에너지",remaining:"kcal 남음",bodyScan:"바디 스캔",mealsToday:"오늘의 식사",noMeals:"식사가 기다리고 있어요",addMeal:"식사 추가",editPlan:"계획 수정",language:"언어",signOut:"로그아웃" },
  id: { welcomeTitle:"Makan seperti juara.",welcomeSub:"Foto, catat, dan makan lebih cerdas dengan Glint.",signup:"Daftar dengan email",login:"Masuk",create:"Buat akun",assessmentTitle:"Buat rencanamu",assessmentSub:"Lima pilihan cepat untuk menyesuaikan Glint.",nameQ:"Pelatih harus memanggilmu apa?",goalQ:"Apa tujuanmu?",activityQ:"Seberapa aktif harimu?",dietQ:"Gaya makan apa yang cocok?",focusQ:"Apa yang paling penting sekarang?",continue:"Lanjut",finish:"Mulai rencana",balanced:"Seimbang",muscle:"Tambah otot",fatLoss:"Kurangi lemak",energy:"Tambah energi",greeting:"Siap isi energi",dailyFuel:"Energi harian",remaining:"kcal tersisa",bodyScan:"Pindai Tubuh",mealsToday:"Makanan hari ini",noMeals:"Piringmu menunggu",addMeal:"Tambah makanan",editPlan:"Ubah rencana",language:"Bahasa",signOut:"Keluar" },
  tr: { welcomeTitle:"Şampiyon gibi beslen.",welcomeSub:"Fotoğrafla, takip et ve Glint ile akıllı beslen.",signup:"E-posta ile kaydol",login:"Giriş yap",create:"Hesap oluştur",assessmentTitle:"Planını oluştur",assessmentSub:"Beş hızlı seçimle Glint'i kişiselleştir.",nameQ:"Koçun sana ne desin?",goalQ:"Hedefin ne?",activityQ:"Ne kadar aktifsin?",dietQ:"Hangi beslenme tarzı sana uygun?",focusQ:"Şu an en önemli şey ne?",continue:"Devam",finish:"Planımı başlat",balanced:"Dengeli",muscle:"Kas yap",fatLoss:"Yağ yak",energy:"Daha fazla enerji",greeting:"Enerji toplamaya hazır",dailyFuel:"Günlük enerji",remaining:"kcal kaldı",bodyScan:"Vücut Taraması",mealsToday:"Bugünkü öğünler",noMeals:"Tabağın seni bekliyor",addMeal:"Öğün ekle",editPlan:"Planı düzenle",language:"Dil",signOut:"Çıkış" },
  ru: { welcomeTitle:"Ешь как чемпион.",welcomeSub:"Снимай, отслеживай и питайся умнее с Glint.",signup:"Регистрация по почте",login:"Войти",create:"Создать аккаунт",assessmentTitle:"Создай свой план",assessmentSub:"Пять быстрых ответов настроят Glint под тебя.",nameQ:"Как тренеру тебя называть?",goalQ:"Какова твоя цель?",activityQ:"Насколько ты активен?",dietQ:"Какой стиль питания подходит?",focusQ:"Что сейчас важнее всего?",continue:"Продолжить",finish:"Начать план",balanced:"Баланс",muscle:"Набор мышц",fatLoss:"Снижение жира",energy:"Больше энергии",greeting:"Готов зарядиться",dailyFuel:"Энергия на день",remaining:"ккал осталось",bodyScan:"Скан тела",mealsToday:"Сегодняшние приёмы пищи",noMeals:"Твоя тарелка ждёт",addMeal:"Добавить еду",editPlan:"Изменить план",language:"Язык",signOut:"Выйти" },
};

export function translate(language: Language, key: string): string {
  return local[language]?.[key] ?? en[key] ?? key;
}

export function languageName(language: Language) {
  return languages.find((item) => item.id === language)?.label ?? "English";
}

export function localeFor(language: Language) {
  return languages.find((item) => item.id === language)?.locale ?? "en-US";
}
